import { View, Text, StyleSheet } from '@react-pdf/renderer';
import { ReportBranding } from '@/types/report';

const s = StyleSheet.create({
  container: {
    position: 'absolute',
    bottom: 30,
    left: 40,
    right: 40,
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
    paddingTop: 10,
    borderTop: 1,
    borderTopColor: '#e2e8f0',
  },
  text: {
    fontSize: 8,
    color: '#94a3b8',
  },
});

interface Props {
  branding: ReportBranding;
}

export function ReportFooter({ branding }: Props) {
  return (
    <View style={s.container}>
      <Text style={s.text}>
        Generated by {branding.companyName || 'AdMirror'} | {branding.websiteUrl || 'admirror.io'}
      </Text>
      <Text style={s.text}>
        Confidential
      </Text>
    </View>
  );
}
